apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-blue
  namespace: nodejs-app
  labels:
    app: nodejs-app
    env: blue
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
      env: blue
  template:
    metadata:
      labels:
        app: nodejs-app
        env: blue
    spec:
      containers:
      - name: nodejs-app
        image: 965202785849.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:51
        ports:
        - containerPort: 3000
        env:
        - name: DEPLOYMENT_VERSION
          value: "v51"
        - name: DEPLOYMENT_ENV
          value: "blue"          
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10