apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-blue
  namespace: nodejs-app
  labels:
    app: nodejs-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
      version: blue
  template:
    metadata:
      labels:
        app: nodejs-app
        version: blue
    spec:
      containers:
      - name: nodejs-app
        image: 965202785849.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:v1
        ports:
        - containerPort: 3000