apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-green
  namespace: nodejs-app
  labels:
    app: nodejs-app
    version: green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nodejs-app
      version: green
  template:
    metadata:
      labels:
        app: nodejs-app
        version: green
    spec:
      containers:
      - name: nodejs-app
        image: 965202785849.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:v2
        ports:
        - containerPort: 3000