apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: nodejs-app
spec:
  selector:
    app: nodejs-app
    env: blue # Initial environment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000