apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: git@github.com:NimalDas/jenkins-argo-eks.git
    targetRevision: main
    ref: values
  - repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.4.2
    helm:
      valueFiles:
      - $values/eks-gitops/jenkins/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true