controller:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: false
    # ingressClassName: nginx
    # annotations:
    #   nginx.ingress.kubernetes.io/rewrite-target: /
    # paths:
    # - /jenkins
    # pathType: Prefix
    # hosts:
    # - jenkins.local
  admin:
    user: admin
    password: "Liverp00l" # Replace with a secure password
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
  persistence:
    enabled: true
    storageClass: "gp2"
    size: 8Gi
  installPlugins:
    - pipeline-stage-view:2.37
    - ssh-agent:latest

agent:
  serviceAccount: jenkins
  image:
    repository: "965202785849.dkr.ecr.us-east-1.amazonaws.com/jenkins-agents"
    tag: "1.0.2-podman-npm"   
